#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "------------------------------------------------------"
echo "Running Post-Reboot Finalization (Part 3)"
echo "------------------------------------------------------"

# -----------------------
# AUR Helper (paru)
# -----------------------
echo "[INFO] Installing AUR helper (paru)..."

# Install base-devel
pacman -Sy --needed --noconfirm base-devel

# Clone and build paru
TEMP_DIR=$(mktemp -d)
git clone https://aur.archlinux.org/paru.git "$TEMP_DIR/paru"
cd "$TEMP_DIR/paru"
makepkg -si --noconfirm
cd /
rm -rf "$TEMP_DIR"

echo "paru installed successfully"

# -----------------------
# Package Installation
# -----------------------
PACKAGES=(
  awww
  btrfs-progs
  pacman-contrib
  reflector
  rsync
  snapper
  tlp
  ufw
  fwupd
  nvme-cli
  git
  man-db
  man-pages
  tldr
  neovim
  bat
  eza
  fastfetch
  btop
  wl-clipboard
  wget
  starship
  stow
  sudo
  zsh
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
  niri
  ly
  waybar
  mako
  swayidle
  swaylock
  wlsunset
  brightnessctl
  blueman
  nm-connection-editor
  playerctl
  syncthing
  thunar
  gvfs
  fuzzel
  rebuild-detector
  fprintd
  fail2ban
)

AUR_PACKAGES=(
  eww-git
  zen-browser-bin
  helium-browser-bin
  minecraft-launcher
)

echo "[INFO] Installing packages..."
pacman -Sy --needed --noconfirm "${PACKAGES[@]}"

paru -Sy --noconfirm "${AUR_PACKAGES[@]}"

# -----------------------
# Zsh Configuration
# -----------------------
echo "[INFO] Configuring Zsh..."
ZSHRC="$HOME/.zshrc"
if [[ ! -f "$ZSHRC" ]]; then
  cat >"$ZSHRC" <<EOF
# Auto-generated by Arch Setup Part 3
export PATH="\$PATH"
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
eval "\$(starship init zsh)"
EOF
  echo "Created basic .zshrc with plugins."
fi

# -----------------------
# Snapper Configuration
# -----------------------
echo "[INFO] Configuring Snapper..."
snapper -c root create-config /

# -----------------------
# Service Enablement
# -----------------------
echo "[INFO] Enabling services..."

# Network & System
systemctl enable NetworkManager.service
systemctl enable fstrim.timer
systemctl enable paccache.timer
systemctl enable reflector.service
systemctl enable snapper-cleanup.timer
systemctl enable snapper-backup.timer
systemctl enable snapper-timeline.timer
systemctl enable fprintd.service
systemctl enable tlp.service
systemctl enable fwupd-refresh.timer
systemctl enable bluetooth.service
systemctl enable systemd-timesyncd.service
systemctl enable fail2ban.service
systemctl enable ly.service

# Firewall
ufw default deny incoming
ufw default allow outgoing
systemctl enable ufw.service

# -----------------------
# Laptop Power Management
# -----------------------
echo "[INFO] Configuring laptop power management..."

# logind.conf
cat >>/etc/systemd/logind.conf <<EOL
# Laptop lid behavior
HandleLidSwitch=suspend-then-hibernate
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=ignore
HoldoffTimeoutSec=30s
EOL

# sleep.conf
cat >>/etc/systemd/sleep.conf <<EOL
[Sleep]
HibernateDelaySec=1h
HibernateOnACPower=no
EOL

# Mask rfkill services (TLP requirement)
systemctl mask systemd-rfkill.service
systemctl mask systemd-rfkill.socket

# -----------------------
# Udev Rules
# -----------------------
echo "[INFO] Creating udev rules..."

# Low battery hibernation
cat >/etc/udev/rules.d/80-lowbat.rules <<EOL
SUBSYSTEM=="power_supply", ATTR{status}=="Discharging", ATTR{capacity}=="[0-5]", RUN+="/usr/bin/systemctl hibernate"
EOL

# Backlight permissions
cat >/etc/udev/rules.d/90-backlight.rules <<EOL
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video \$sys\$devpath/brightness", RUN+="/bin/chmod g+w \$sys\$devpath/brightness"
EOL

# Initialize Mac Superdrive
cat >/etc/udev/rules.d/99-mac-superdrive.rules <<EOL
# Apple SuperDrive initialization rule
# See: https://gist.github.com/yookoala/818c1ff057e3d965980b7fd3bf8f77a6
ACTION=="add", ATTRS{idProduct}=="1500", ATTRS{idVendor}=="05ac", DRIVERS=="usb", RUN+="/usr/bin/sg_raw --cmdset=1 %r/sr%n EA 00 00 00 00 00 01"
EOL

# Shared mount points
cat >/etc/udev/rules.d/99-udisks2.rules <<EOL
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="1"
EOL

# Reload udev rules
udevadm control --reload-rules

# -----------------------
# ACPI Reboot Fix
# -----------------------
echo "[INFO] Applying ACPI reboot fix..."
sed -i 's/^#RebootWatchdogSec=.*/RebootWatchdogSec=0/' /etc/systemd/system.conf
# If the line doesn't exist, add it
grep -q "^RebootWatchdogSec=" /etc/systemd/system.conf || echo "RebootWatchdogSec=0" >>/etc/systemd/system.conf

# -----------------------
# Mirrorlist Update
# -----------------------
echo "[INFO] Updating mirrorlist..."
reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist

# -----------------------
# 11. Cleanup
# -----------------------
pacman -Sc --noconfirm

# -----------------------
# Final Summary
# -----------------------
echo "------------------------------------------------------"
echo "Setup Complete!"
echo "  - UKI configured with presets"
echo "  - paru AUR helper installed"
echo "  - Zsh configured with plugins"
echo "  - Snapper configured for snapshots"
echo "  - All services enabled"
echo "  - Laptop power management configured"
echo "  - Udev rules applied"
echo "  - Firewall active"
echo "------------------------------------------------------"
echo "Next: Reboot and log in with your user."
echo "------------------------------------------------------"
