#!/bin/bash

# Packages
# retrieve full list of packages with 'pacman -Qentq'

# Security & Battery & Network
pacman --needed --noconfirm -Sy fail2ban ufw wireguard-tools tlp nm-connection-editor

# Terminal & Shells
pacman --needed --noconfirm -Sy alacritty dash zsh zsh-autosuggestions zsh-completions zsh-syntax-highlighting wget youtube-dl

# Terminal Apps
pacman --needed --noconfirm -Sy btop checkbashisms exa fwupd man-db man-pages tldr nano nano-syntax-highlighting \
nvme-cli pacman-contrib reflector snapper starship tree

# Drive Management
pacman --needed --noconfirm -Sy gparted exfat-utils ntfs-3g android-tools rsync

#Bluetooth & Audio
pacman --needed --noconfirm -Sy blueman bluez-utils alsa-utils pipewire wireplumber pipewire-pulse pipewire-alsa pamixer

# Windows Manager/Config shortcuts
pacman --needed --noconfirm -Sy sway grim slurp imv rofi dunst

# File Manager
pacman --needed --noconfirm -Sy nemo nemo-fileroller gvfs-mtp xdg-user-dirs

# Fonts
pacman --needed --noconfirm -Sy ttf-font-awesome ttf-hack powerline-fonts

# Misc.
pacman --needed --noconfirm -Sy galculator calibre gimp libreoffice-still vlc fprintd acpilight

#######WORK IN PROGRESS################

## Get resume offset for BTRFS swapfile
cd /root/ || exit
curl -LJO https://raw.githubusercontent.com/osandov/osandov-linux/master/scripts/btrfs_map_physical.c
gcc -O2 -o btrfs_map_physical btrfs_map_physical.c
rm btrfs_map_physical.c
# I wouldn't fully trust this and make sure your verify after reboot
printf "
#######################################################\n### I WOULD CHECK THIS AFTER YOU ARE IN YOUR SYSTEM ###\n###   WORK IN PROGRESS section 'finishing_touches'  ###\n#######################################################"
sleep 5
OFFSET=$(./btrfs_map_physical /swap/swapfile | awk -F '\t' 'FNR == 2 {print $NF}')
PAGESIZE=$(getconf PAGESIZE)
((RESUME_OFFSET=$OFFSET/$PAGESIZE))
sleep 5
UUID=$(blkid | grep mapper | awk '{print $2}' | tr -d '"')
CRYPTUUID=$(blkid | grep p2 | awk '{print $2}' | tr -d '"')

#https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Hibernation_into_swap_file_on_Btrfs
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet"/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet mem_sleep_default=deep resume='$UUID' resume_offset='$RESUME_OFFSET'"/' /etc/default/grub
sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cryptdevice='$CRYPTUUID':root root=/dev/mapper/root net.ifnames=0"/' /etc/default/grub
sed -i 's/#GRUB_ENABLE_CRYPTODISK=y/GRUB_ENABLE_CRYPTODISK=y/' /etc/default/grub
sed -i 's/#GRUB_SAVEDEFAULT=true/GRUB_SAVEDEFAULT=true/' /etc/default/grub
sed -i 's/GRUB_DEFAULT=0/GRUB_DEFAULT=saved/' /etc/default/grub

##############
##APP SETUP ##
##############

# Notifications Setup Using 'dunst'
pacman --needed --noconfirm -S dunst libnotify
touch /usr/share/dbus-1/services/org.freedesktop.Notifications.service
tee /usr/share/dbus-1/services/org.freedesktop.Notifications.service > /dev/null <<EOT
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/bin/dunst
EOT

##############
##AUR HELPER##
##############
# PARU Setup
pacman --needed -S base-devel
git clone https://aur.archlinux.org/paru.git && cd paru || return
makepkg -si
cd .. && rm -dR paru
# AUR PACKAGES
# retrieved with 'pacman -Qemtq'
paru -S brave-bin minecraft-launcher nerd-fonts-complete ttf-ms-fonts vscodium-bin wev wlsunset a2ln
exit && cd ~

# Enabling extra services
systemctl enable tlp.service
systemctl mask systemd-rfkill.service
systemctl mask systemd-rfkill.socket
systemctl enable bluetooth.service
systemctl enable systemd-timesyncd.service
systemctl --user enable --now pipewire-pulse.socket

# UFW
systemctl enable ufw.service
sudo ufw enable

# Logind.conf settings
sed -i 's/#HandleLidSwitch=suspend/HandleLidSwitch=hibernate\\\nHandleLidSwitchExternalPower=suspend/' /etc/systemd/logind.conf
sed -i 's/#HoldoffTimeoutSec=30s/HoldoffTimeoutSec=30s/' /etc/systemd/logind.conf

# Laptop Settings
touch /etc/udev/rules.d/99-lowbat.rules
tee -a /etc/udev/rules.d/99-lowbat.rules > /dev/null <<EOT
# Suspend the system when battery level drops to 5% or lower
SUBSYSTEM=="power_supply", ATTR{status}=="Discharging", ATTR{capacity}=="[0-5]", RUN+="/usr/bin/systemctl hibernate"
EOT

# acpi issue
sed -i 's/#RebootWatchdogSec=0/RebootWatchdogSec=0/' /etc/systemd/system.conf

# Stuttering and periodic freeze/No longer needed but doesn't cause issue's
echo -e "options i915 enable_psr=0" >> /etc/modprobe.d/i915.conf

# Change /bin/sh to dash instead of bash
ln -sfT dash /usr/bin/sh
mkdir /etc/pacman.d/hooks
touch /etc/pacman.d/hooks/dashbinsh.hook
tee -a /etc/pacman.d/hooks/dashbinsh.hook  > /dev/null <<EOT
[Trigger]
Type = Package
Operation = Install
Operation = Upgrade
Target = bash

[Action]
Description = Re-pointing /bin/sh symlink to dash...
When = PostTransaction
Exec = /usr/bin/ln -sfT dash /usr/bin/sh
Depends = dash
EOT
